field: 85898001-9c9c-4d46-abf9-a928e44f0d48 # Body Content
fieldLayouts:
  73ac25bc-ace9-4aa6-ba1d-9211b5c06027:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 735b5e6e-8026-4de4-8e32-14e03d975565 # Image
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c9b2074e-9c0c-42ca-912b-da62df8b651a
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 11f1c188-401c-44c4-bd0e-2b6d7b311fc6 # Align
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a7d2f31c-4840-49d7-b930-6ca71180731c
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 871e0a60-ea70-4650-91f2-746c9bc2de41 # Aspect Ratio
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 317ec3fc-8fee-45dc-a2e6-2770b50e0ead
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 4bf7eb3c-ca42-4327-97e2-77533fc27a61 # Caption
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 649ac495-89c5-4501-a812-7f6b0c153d0a
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: c8a6470e-a8da-46c4-ae23-4eb68d320a66 # Show in Sites
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c6e29d16-59d9-4538-87f6-021cf48891f7
            userCondition: null
            warning: null
            width: 25
        name: Content
        uid: c7f52bda-4083-406b-982c-63def615500a
        userCondition: null
fields:
  4bf7eb3c-ca42-4327-97e2-77533fc27a61: # Caption
    columnSuffix: zpaqwywa
    contentColumnType: string(240)
    fieldGroup: null
    handle: caption
    instructions: null
    name: Caption
    searchable: true
    settings:
      byteLimit: null
      charLimit: 60
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: language
    type: craft\fields\PlainText
  11f1c188-401c-44c4-bd0e-2b6d7b311fc6: # Align
    columnSuffix: hvxizuqa
    contentColumnType: string
    fieldGroup: null
    handle: align
    instructions: null
    name: Align
    searchable: false
    settings:
      columnType: string
      options:
        -
          __assoc__:
            -
              - label
              - Default
            -
              - value
              - ''
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Wide
            -
              - value
              - wide
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  735b5e6e-8026-4de4-8e32-14e03d975565: # Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: null
    name: Image
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - image
      branchLimit: null
      defaultUploadLocationSource: 'volume:5a0be839-14a2-465e-a504-bb63dd0281e9' # Images
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: 1
      minRelations: null
      previewMode: thumbs
      restrictFiles: true
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:5a0be839-14a2-465e-a504-bb63dd0281e9' # Images
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
          -
            - conditionRules
            -
              -
                __assoc__:
                  -
                    - class
                    - craft\elements\conditions\assets\WidthConditionRule
                  -
                    - uid
                    - c2f227f4-49cc-4b5a-ab14-43a864cbfaea
                  -
                    - operator
                    - '>='
                  -
                    - value
                    - '800'
                  -
                    - maxValue
                    - ''
      selectionLabel: 'Select an image'
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      sources:
        - 'volume:5a0be839-14a2-465e-a504-bb63dd0281e9' # Images
      targetSiteId: null
      validateRelatedElements: true
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  871e0a60-ea70-4650-91f2-746c9bc2de41: # Aspect Ratio
    columnSuffix: rizfjoen
    contentColumnType: string
    fieldGroup: null
    handle: aspectRatio
    instructions: null
    name: 'Aspect Ratio'
    searchable: false
    settings:
      columnType: string
      options:
        -
          __assoc__:
            -
              - label
              - 'Default (16/9)'
            -
              - value
              - default
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - 'Full Height'
            -
              - value
              - fullHeight
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Square
            -
              - value
              - square
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Slim (21/9)'
            -
              - value
              - slim
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Classic (4/3)'
            -
              - value
              - classic
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  c8a6470e-a8da-46c4-ae23-4eb68d320a66: # Show in Sites
    columnSuffix: bvyvbpkh
    contentColumnType: string
    fieldGroup: null
    handle: showInSites
    instructions: null
    name: 'Show in Sites'
    searchable: false
    translationKeyFormat: null
    translationMethod: none
    type: modules\main\fields\SiteField
handle: image
name: Image
sortOrder: 3
