field: e62d63b0-c299-42ce-aeef-86a69f7e676c # SEO Fields
fieldLayouts:
  a3a223e7-de48-4b77-9d19-7fd60f6e0131:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: b0cfc7f4-d446-41bb-87ab-dc16b1481540 # Alternative Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bc0be446-128a-4e51-81f8-7ba23b91142a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9c7e95a7-7a87-46ad-974e-8ce3846ef68b # Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 07ad2848-4e40-43cc-bd11-72d61f7141a9
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 34581043-4880-49b9-b16a-cba691fa21f3 # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 02950812-f12a-42cd-a1f7-e20bd7f8f089
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 90724a6b-55ad-446f-be50-7aea7e1fb067 # Robots
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 49714142-2f02-44e9-a475-5dd1f7d878ce
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 9fc96fef-7f12-483f-aee5-9c03aece82ad
        userCondition: null
fields:
  9c7e95a7-7a87-46ad-974e-8ce3846ef68b: # Description
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: description
    instructions: null
    name: Description
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: 4
      multiline: true
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: language
    type: craft\fields\PlainText
  90724a6b-55ad-446f-be50-7aea7e1fb067: # Robots
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: robots
    instructions: null
    name: Robots
    searchable: true
    settings:
      columnType: string
      options:
        -
          __assoc__:
            -
              - label
              - all
            -
              - value
              - all
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - noindex
            -
              - value
              - noindex
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - nofollow
            -
              - value
              - nofollow
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  34581043-4880-49b9-b16a-cba691fa21f3: # Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: null
    name: Image
    searchable: true
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - image
      branchLimit: null
      defaultUploadLocationSource: 'volume:5a0be839-14a2-465e-a504-bb63dd0281e9' # Images
      defaultUploadLocationSubpath: seo
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: 1
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:5a0be839-14a2-465e-a504-bb63dd0281e9' # Images
      restrictedLocationSubpath: null
      selectionLabel: 'Select image'
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
      sources:
        - 'volume:5a0be839-14a2-465e-a504-bb63dd0281e9' # Images
      targetSiteId: null
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  b0cfc7f4-d446-41bb-87ab-dc16b1481540: # Alternative Title
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: alternativeTitle
    instructions: null
    name: 'Alternative Title'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: language
    type: craft\fields\PlainText
handle: settings
name: Settings
sortOrder: 1
