fieldLayouts:
  9be2749d-72b7-48fa-afa7-d1f2b7e7b091:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: f3031dfd-8076-45b3-b767-8c73fe441e6b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 710a1bd0-9eeb-4721-9493-f2d7dead49ee # Body
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 16b48c34-ffb4-4f39-8001-c4a9d116e0ee
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7602aac5-c98e-44bd-8570-457a85b8abad # Criteria
            instructions: "Must be valid JSON.\r\n\r\nBesides query criteria you can use `\"showMetaData\": true` , `\"layout\":\"card/cardlet\"` `\"width\":\"md/xl\"`"
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6bc1c257-97ba-4296-805f-eb0121fcfa8c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 08f7545c-870e-4727-a418-660af19052ea # CTA Buttons
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f8c89bf6-7e51-4624-ae7b-492a2591252b
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 9982bc63-ab67-470e-8a48-e935f6491770
        userCondition: null
handle: cards
hasTitleField: true
name: Cards
section: a1bd5e0e-3bf9-428d-a4f5-bebd6b3c1692 # Content Section
sortOrder: 5
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
