fieldLayouts:
  35aac453-6959-4771-9712-cb98f5a45da0:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 23e88f1c-1490-4ee0-9514-ebc54e2dfce1
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\elements\conditions\LevelConditionRule
                  operator: '='
                  uid: 26bc4c45-6da3-484a-b16e-a9111915ed6b
                  value: '2'
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: e2e51276-3783-49cb-9ed0-22ae364fd49a # Menu Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 606761c5-6bcf-4d72-acc4-08e97d2f6046
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 1f5834fd-ed0d-466a-b4dd-2891fd144893 # Show Structure Navigation
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e4ea9583-0b94-4154-bae7-a0d6bb47ad28
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 400d2e7a-d260-459d-b16d-bc388f093106 # Tagline
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 81811389-64d6-4ab9-8eee-543834b5b690
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 85898001-9c9c-4d46-abf9-a928e44f0d48 # Body Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b3749e2b-fda8-411d-b55e-306b27632de2
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 805db790-0bd9-4591-905d-34133e531ece
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: e62d63b0-c299-42ce-aeef-86a69f7e676c # SEO Fields
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f3fda0e8-90e0-4c53-955e-d0be31931b2e
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: 98c055d9-9b56-486b-b2d0-99fc3dee847e
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: 84b98802-2548-4aed-b67e-fc97f6ed9e30 # Page
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: language
