fieldLayouts:
  67348023-43a0-47ff-85c1-e817fd411a16:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: e63c5223-e2e9-434a-8fdd-22bb4e1b1a80
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 95358052-5e25-4a5d-bd52-58078b1a5aa2 # FAQs
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a976c09c-82cd-4b61-9a53-6408dc411437
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 9983cef9-c592-4580-af7d-1899898da37e
        userCondition: null
handle: faqs
hasTitleField: true
name: FAQs
section: a1bd5e0e-3bf9-428d-a4f5-bebd6b3c1692 # Content Section
sortOrder: 7
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: language
