fieldLayouts:
  a9532587-12ca-483b-9e53-5aa73b26666a:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dismissible: true
            elementCondition: null
            style: warning
            tip: 'The Emaillist plugin must be installed!'
            type: craft\fieldlayoutelements\Tip
            uid: d9096f6b-a37f-474b-8d4d-d8d77acd16b6
            userCondition: null
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: c7f51693-c9c4-4b55-9546-6325a2b0e99c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: bbc46fd7-2b24-431f-a7d1-aedf86a6c169 # Handle
            instructions: 'e.g. ''newsletter'''
            label: 'Email List Id'
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 93f5d6a4-9902-4056-bdc6-ea8a31755ad2
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 710a1bd0-9eeb-4721-9493-f2d7dead49ee # Body
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 22cc98aa-a486-49b9-a0e2-bc1cb9b3d6b2
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 502456b5-d67c-412d-927e-d06e8f662eac # Button Caption
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 56b477a2-afa6-4bca-9689-a11e7348cb7f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: f7bd979f-701a-4c93-b239-5f5ed2a577a3
        userCondition: null
handle: newsletter
hasTitleField: true
name: Newsletter
section: a1bd5e0e-3bf9-428d-a4f5-bebd6b3c1692 # Content Component
sortOrder: 8
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: language
