columnSuffix: null
contentColumnType: string
fieldGroup: c38953ca-ba84-4992-8deb-65aa2fc40b34 # Hero Area
handle: heroImage
instructions: 'Full screen width'
name: 'Hero Image'
searchable: false
settings:
  allowSelfRelations: false
  allowSubfolders: false
  allowUploads: true
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:5a0be839-14a2-465e-a504-bb63dd0281e9' # Images
  defaultUploadLocationSubpath: null
  localizeRelations: false
  maxRelations: 1
  minRelations: null
  previewMode: thumbs
  restrictFiles: true
  restrictLocation: false
  restrictedDefaultUploadSubpath: null
  restrictedLocationSource: 'volume:5a0be839-14a2-465e-a504-bb63dd0281e9' # Images
  restrictedLocationSubpath: null
  selectionCondition:
    __assoc__:
      -
        - elementType
        - craft\elements\Asset
      -
        - fieldContext
        - global
      -
        - class
        - craft\elements\conditions\assets\AssetCondition
      -
        - conditionRules
        -
          -
            __assoc__:
              -
                - class
                - craft\elements\conditions\assets\WidthConditionRule
              -
                - uid
                - bcd4f2f0-39b4-4ad0-bc1b-1b4b30b07c51
              -
                - operator
                - '>'
              -
                - value
                - '1800'
  selectionLabel: null
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  source: null
  sources:
    - 'volume:5a0be839-14a2-465e-a504-bb63dd0281e9' # Images
  targetSiteId: null
  validateRelatedElements: false
  viewMode: large
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
