description: null
handle: contentEditors
name: 'Content Editors'
permissions:
  - accesscp
  - accesscpwhensystemisoff
  - accesssitewhensystemisoff
  - 'createentries:27127353-b8d1-4c07-a2af-7a273ad8f1f6' # Hero Area
  - 'createentries:2f93cb45-a9ce-4284-8848-9eb001fb8a1c' # News
  - 'createentries:5042338b-5f7b-4535-96bb-578a829e987c' # Topic
  - 'createentries:84b98802-2548-4aed-b67e-fc97f6ed9e30' # Page
  - 'createentries:a1bd5e0e-3bf9-428d-a4f5-bebd6b3c1692' # Content Component
  - 'createentries:abd279ac-58c4-41dc-ac32-d2e388e34252' # Legal
  - 'createentries:fcbda6e5-a26a-4efb-800a-a67a44a88fa1' # Person
  - 'createfolders:5a0be839-14a2-465e-a504-bb63dd0281e9' # Images
  - 'createfolders:ed627edd-73bd-4b75-8684-f410bf4e4b9d' # Temporary Images
  - 'deleteassets:5a0be839-14a2-465e-a504-bb63dd0281e9' # Images
  - 'deleteassets:ed627edd-73bd-4b75-8684-f410bf4e4b9d' # Temporary Images
  - 'deleteentries:27127353-b8d1-4c07-a2af-7a273ad8f1f6' # Hero Area
  - 'deleteentries:2f93cb45-a9ce-4284-8848-9eb001fb8a1c' # News
  - 'deleteentries:5042338b-5f7b-4535-96bb-578a829e987c' # Topic
  - 'deleteentries:84b98802-2548-4aed-b67e-fc97f6ed9e30' # Page
  - 'deleteentries:a1bd5e0e-3bf9-428d-a4f5-bebd6b3c1692' # Content Component
  - 'deleteentries:abd279ac-58c4-41dc-ac32-d2e388e34252' # Legal
  - 'deleteentries:fcbda6e5-a26a-4efb-800a-a67a44a88fa1' # Person
  - 'deletepeerassets:5a0be839-14a2-465e-a504-bb63dd0281e9' # Images
  - 'deletepeerassets:ed627edd-73bd-4b75-8684-f410bf4e4b9d' # Temporary Images
  - 'deletepeerentries:27127353-b8d1-4c07-a2af-7a273ad8f1f6' # Hero Area
  - 'deletepeerentries:2f93cb45-a9ce-4284-8848-9eb001fb8a1c' # News
  - 'deletepeerentries:5042338b-5f7b-4535-96bb-578a829e987c' # Topic
  - 'deletepeerentries:84b98802-2548-4aed-b67e-fc97f6ed9e30' # Page
  - 'deletepeerentries:a1bd5e0e-3bf9-428d-a4f5-bebd6b3c1692' # Content Component
  - 'deletepeerentries:abd279ac-58c4-41dc-ac32-d2e388e34252' # Legal
  - 'deletepeerentries:fcbda6e5-a26a-4efb-800a-a67a44a88fa1' # Person
  - 'deletepeerentrydrafts:27127353-b8d1-4c07-a2af-7a273ad8f1f6' # Hero Area
  - 'deletepeerentrydrafts:2f93cb45-a9ce-4284-8848-9eb001fb8a1c' # News
  - 'deletepeerentrydrafts:5042338b-5f7b-4535-96bb-578a829e987c' # Topic
  - 'deletepeerentrydrafts:71c1782e-c5bc-4d87-840e-0a4c1a643eff' # Site Info
  - 'deletepeerentrydrafts:84b98802-2548-4aed-b67e-fc97f6ed9e30' # Page
  - 'deletepeerentrydrafts:a1bd5e0e-3bf9-428d-a4f5-bebd6b3c1692' # Content Component
  - 'deletepeerentrydrafts:abd279ac-58c4-41dc-ac32-d2e388e34252' # Legal
  - 'deletepeerentrydrafts:fcbda6e5-a26a-4efb-800a-a67a44a88fa1' # Person
  - 'editimages:5a0be839-14a2-465e-a504-bb63dd0281e9' # Images
  - 'editimages:ed627edd-73bd-4b75-8684-f410bf4e4b9d' # Temporary Images
  - 'editpeerimages:5a0be839-14a2-465e-a504-bb63dd0281e9' # Images
  - 'editpeerimages:ed627edd-73bd-4b75-8684-f410bf4e4b9d' # Temporary Images
  - 'editsite:5b0c38db-9ab4-47d8-b4a7-913710c08ca6' # English
  - 'editsite:dbf50cb2-37c8-45f7-b375-dcb93e09691b' # Deutsch
  - 'replacefiles:5a0be839-14a2-465e-a504-bb63dd0281e9' # Images
  - 'replacefiles:ed627edd-73bd-4b75-8684-f410bf4e4b9d' # Temporary Images
  - 'replacepeerfiles:5a0be839-14a2-465e-a504-bb63dd0281e9' # Images
  - 'replacepeerfiles:ed627edd-73bd-4b75-8684-f410bf4e4b9d' # Temporary Images
  - 'saveassets:5a0be839-14a2-465e-a504-bb63dd0281e9' # Images
  - 'saveassets:ed627edd-73bd-4b75-8684-f410bf4e4b9d' # Temporary Images
  - 'saveentries:27127353-b8d1-4c07-a2af-7a273ad8f1f6' # Hero Area
  - 'saveentries:2f93cb45-a9ce-4284-8848-9eb001fb8a1c' # News
  - 'saveentries:5042338b-5f7b-4535-96bb-578a829e987c' # Topic
  - 'saveentries:71c1782e-c5bc-4d87-840e-0a4c1a643eff' # Site Info
  - 'saveentries:84b98802-2548-4aed-b67e-fc97f6ed9e30' # Page
  - 'saveentries:a1bd5e0e-3bf9-428d-a4f5-bebd6b3c1692' # Content Component
  - 'saveentries:abd279ac-58c4-41dc-ac32-d2e388e34252' # Legal
  - 'saveentries:fcbda6e5-a26a-4efb-800a-a67a44a88fa1' # Person
  - 'savepeerassets:5a0be839-14a2-465e-a504-bb63dd0281e9' # Images
  - 'savepeerassets:ed627edd-73bd-4b75-8684-f410bf4e4b9d' # Temporary Images
  - 'savepeerentries:27127353-b8d1-4c07-a2af-7a273ad8f1f6' # Hero Area
  - 'savepeerentries:2f93cb45-a9ce-4284-8848-9eb001fb8a1c' # News
  - 'savepeerentries:5042338b-5f7b-4535-96bb-578a829e987c' # Topic
  - 'savepeerentries:84b98802-2548-4aed-b67e-fc97f6ed9e30' # Page
  - 'savepeerentries:a1bd5e0e-3bf9-428d-a4f5-bebd6b3c1692' # Content Component
  - 'savepeerentries:abd279ac-58c4-41dc-ac32-d2e388e34252' # Legal
  - 'savepeerentries:fcbda6e5-a26a-4efb-800a-a67a44a88fa1' # Person
  - 'savepeerentrydrafts:27127353-b8d1-4c07-a2af-7a273ad8f1f6' # Hero Area
  - 'savepeerentrydrafts:2f93cb45-a9ce-4284-8848-9eb001fb8a1c' # News
  - 'savepeerentrydrafts:5042338b-5f7b-4535-96bb-578a829e987c' # Topic
  - 'savepeerentrydrafts:71c1782e-c5bc-4d87-840e-0a4c1a643eff' # Site Info
  - 'savepeerentrydrafts:84b98802-2548-4aed-b67e-fc97f6ed9e30' # Page
  - 'savepeerentrydrafts:a1bd5e0e-3bf9-428d-a4f5-bebd6b3c1692' # Content Component
  - 'savepeerentrydrafts:abd279ac-58c4-41dc-ac32-d2e388e34252' # Legal
  - 'savepeerentrydrafts:fcbda6e5-a26a-4efb-800a-a67a44a88fa1' # Person
  - 'viewassets:5a0be839-14a2-465e-a504-bb63dd0281e9' # Images
  - 'viewassets:ed627edd-73bd-4b75-8684-f410bf4e4b9d' # Temporary Images
  - 'viewentries:27127353-b8d1-4c07-a2af-7a273ad8f1f6' # Hero Area
  - 'viewentries:2f93cb45-a9ce-4284-8848-9eb001fb8a1c' # News
  - 'viewentries:5042338b-5f7b-4535-96bb-578a829e987c' # Topic
  - 'viewentries:71c1782e-c5bc-4d87-840e-0a4c1a643eff' # Site Info
  - 'viewentries:84b98802-2548-4aed-b67e-fc97f6ed9e30' # Page
  - 'viewentries:a1bd5e0e-3bf9-428d-a4f5-bebd6b3c1692' # Content Component
  - 'viewentries:abd279ac-58c4-41dc-ac32-d2e388e34252' # Legal
  - 'viewentries:fcbda6e5-a26a-4efb-800a-a67a44a88fa1' # Person
  - 'viewpeerassets:5a0be839-14a2-465e-a504-bb63dd0281e9' # Images
  - 'viewpeerassets:ed627edd-73bd-4b75-8684-f410bf4e4b9d' # Temporary Images
  - 'viewpeerentries:27127353-b8d1-4c07-a2af-7a273ad8f1f6' # Hero Area
  - 'viewpeerentries:2f93cb45-a9ce-4284-8848-9eb001fb8a1c' # News
  - 'viewpeerentries:5042338b-5f7b-4535-96bb-578a829e987c' # Topic
  - 'viewpeerentries:84b98802-2548-4aed-b67e-fc97f6ed9e30' # Page
  - 'viewpeerentries:a1bd5e0e-3bf9-428d-a4f5-bebd6b3c1692' # Content Component
  - 'viewpeerentries:abd279ac-58c4-41dc-ac32-d2e388e34252' # Legal
  - 'viewpeerentries:fcbda6e5-a26a-4efb-800a-a67a44a88fa1' # Person
  - 'viewpeerentrydrafts:27127353-b8d1-4c07-a2af-7a273ad8f1f6' # Hero Area
  - 'viewpeerentrydrafts:2f93cb45-a9ce-4284-8848-9eb001fb8a1c' # News
  - 'viewpeerentrydrafts:5042338b-5f7b-4535-96bb-578a829e987c' # Topic
  - 'viewpeerentrydrafts:71c1782e-c5bc-4d87-840e-0a4c1a643eff' # Site Info
  - 'viewpeerentrydrafts:84b98802-2548-4aed-b67e-fc97f6ed9e30' # Page
  - 'viewpeerentrydrafts:a1bd5e0e-3bf9-428d-a4f5-bebd6b3c1692' # Content Component
  - 'viewpeerentrydrafts:abd279ac-58c4-41dc-ac32-d2e388e34252' # Legal
  - 'viewpeerentrydrafts:fcbda6e5-a26a-4efb-800a-a67a44a88fa1' # Person
