defaultPlacement: end
enableVersioning: true
handle: page
name: Page
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  5b0c38db-9ab4-47d8-b4a7-913710c08ca6: # English
    enabledByDefault: true
    hasUrls: true
    template: _sections/page
    uriFormat: '{parent.uri|replace({''__home__'': ''''})}/{slug}'
  dbf50cb2-37c8-45f7-b375-dcb93e09691b: # Deutsch
    enabledByDefault: true
    hasUrls: true
    template: _sections/page
    uriFormat: '{parent.uri|replace({''__home__'': ''''})}/{slug}'
structure:
  maxLevels: null
  uid: 90b11039-2eba-48d9-9e4a-bcbb8797204c
type: structure
